extends: airbnb-base

env:
  node: true
  es6: true

rules:
  max-len: [error, 240]
  semi: [error, always]
  comma-dangle: [error, always-multiline]
  quotes: [error, single]
  no-plusplus: off
  object-curly-spacing: [error, never]
  object-curly-newline: off
  no-param-reassign: off
  no-await-in-loop: off
  no-empty: [error, allowEmptyCatch: true]
  import/prefer-default-export: off
  no-nested-ternary: off
  linebreak-style: off
  global-require: off
  arrow-parens: off
